baseURL = "https://s0521.github.io/"
languageCode = "utf-8"
title = "Yongchao Fu | 付永超"
theme = "ivy"
disqusShortname = "Yongchao"
enableEmoji = true
preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"
rssLimit = 100
googleAnalytics = "UA-138584476-1"

[params]
  description = "Personal website of Yongchao Fu; 付永超的个人网站"
  footer = "&copy; [Yongchao Fu](https://s0521.github.io/) 2019 - 2023"
  disqusURL = "https://s0521.github.io/"
  AuthorName = "Yongchao Fu"
  GitHubUser = "s0521"
  ListOfFoo = ["foo1", "foo2"]
  SidebarRecentLimit = 5
  Subtitle = "这是付永超使用hugo构建的网站"
  author = {en = "Yongchao Fu", cn = "付永超"}
  logo = {img = "/images/logo.png" , url = "/" , alt = "Yongchao Fu" , tag = ""}
  lang = {edit = {cn = "编辑"}, license ={cn = "版权"}, subscribe = {cn = "订阅"}}
  githubContentURL = "https://github.com/s0521/Phoenix/edit/master/content/"
  customJS = [ "js/fix-toc.js", "js/center-img.js", "js/right-quote.js", "js/no-highlight.js", "js/fix-footnote.js", "js/math-code.js", "js/external-link.js", "js/alt-title.js", "js/header-link.js"]
  #customJS = {js/fix-toc.js, js/center-img.js, js/right-quote.js, js/no-highlight.js, js/fix-footnote.js, js/math-code.js, js/external-link.js, js/alt-title.js, js/header-link.js }
  
  highlightjsVersion = "9.12.0"
  highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
  highlightjsLang = ["R", "r", "yaml", "tex", "vbnet", "SAS", "sas"]
  #highlightjsTheme = "github-gist"
  highlightjsTheme = "github"
  
  enableGitalk = true
[params.gitalk]
  owner = "s0521"
  repo = "s0521.github.io"
  client_id = "8d1421e8a6cfe245f5f2"
  client_secret = "7b842e02dbc3388b936bdc37373643f6379b9fb2"
  
  [permalinks]
  posts = "/:year/:month/:slug/"
  cn = "/cn/:year/:month/:slug/"
  en = "/en/:year/:month/:slug/"
 
[menu]
  [[menu.main]]
    name = "About"
    url = "/en/about/"
    weight = 1
  [[menu.main]]
    name = "Blog"
    url = "/en/"
    weight = 2
  [[menu.main]]
	  name = "关于"
    url = "/cn/about/"
    weight = 3
  [[menu.main]]
	  name = "博客"
    url = "/cn/"
    weight = 4
	
  [[menu.en]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.en]]
    name = "About"
    url = "/en/about/"
    weight = 2
  [[menu.en]]
    name = "Blog"
    url = "/en/"
    weight = 3
  [[menu.en]]
    name = "Vitae"
    url = "/en/vitae/"
    weight = 4
  [[menu.en]]
    name = "中文"
    url = "/cn/"
    weight = 5
	
  [[menu.cn]]
    name = "主页"
    url = "/"
    weight = 1
  [[menu.cn]]
    name = "关于"
    url = "/cn/about/"
    weight = 2
  [[menu.cn]]
    name = "博客"
    url = "/cn/"
    weight = 3
  [[menu.cn]]
    name = "简历"
    url = "/cn/vitae/"
    weight = 4
  [[menu.cn]]
    name = "English"
    url = "/en/"
    weight = 5
  [[menu.cn]]
    name = "捐助"
    url = "/cn/gift/"
	
