baseURL = "https://s0521.github.io/"
languageCode = "utf-8"
title = "Yongchao Fu | 付永超"
theme = "ivy"
disqusShortname = "Yongchao"
enableEmoji = true
preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"
rssLimit = 100

[params]
  description = "Personal website of Yongchao Fu; 付永超的个人网站"
  footer = "&copy; [Yongchao Fu](https://s0521.github.io/) 2019 - 2020"
  disqusURL = "https://s0521.github.io/"
  AuthorName = "Yongchao Fu"
  GitHubUser = "s0521"
  ListOfFoo = ["foo1", "foo2"]
  SidebarRecentLimit = 5
  Subtitle = "这是付永超使用hugo构建的网站"
  [[params.author]]
    en = "Yongchao Fu"
    cn = "付永超"
  [[params.logo]]
      img = "/images/logo.png"
      url = "/"
      alt = "Yongchao Fu"
      tag = ""

[permalinks]
  posts = "/:year/:month/:slug/"
  cn = "/cn/:year/:month/:slug/"
  en = "/en/:year/:month/:slug/"
 
[menu]
  [[menu.main]]
    name = "About"
    url = "/en/about/"
    weight = 1
  [[menu.main]]
    name = "Blog"
    url = "/en/"
    weight = 2
  [[menu.main]]
	  name = "关于"
    url = "/cn/about/"
    weight = 3
  [[menu.main]]
	  name = "博客"
    url = "/cn/"
    weight = 4
	
  [[menu.en]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.en]]
    name = "About"
    url = "/en/about/"
    weight = 2
  [[menu.en]]
    name = "Blog"
    url = "/en/"
    weight = 3
  [[menu.en]]
    name = "中文"
    url = "/cn/"
    weight = 4
	
  [[menu.cn]]
    name = "主页"
    url = "/"
    weight = 1
  [[menu.cn]]
    name = "关于"
    url = "/cn/about/"
    weight = 2
  [[menu.cn]]
    name = "博客"
    url = "/en/"
    weight = 3
  [[menu.cn]]
    name = "Englih"
    url = "/cn/"
    weight = 4
