[build]
command = "hugo"
publish = "public"
[build.environment]
HUGO_VERSION = "0.81.0"

[context]
[context.branch-deploy]
command = "hugo -F -b $DEPLOY_PRIME_URL"
[context.deploy-preview]
command = "hugo -F -b $DEPLOY_PRIME_URL"
[context.production]
[context.production.environment]
HUGO_ENV = "production"

[[redirects]]
from = "https://quiet-malabi-862576.netlify.app/"
to = "https://s0521.github.io/"
force = true